### ISSUE TITLE
Improve Visualization

### ISSUE THREAD

**Issue by ardimasp** [raizulfi/Music-player-FSM#1]
Just to be fair with others, please use ANSI C characters to replace your old display with the new one in your visualization. You can refer to your friends' work for that.

**Comment by raizulfi** [comment]
hello sir, are you saying that there's like a reset display rather then keep printing the result over and over again?

**Comment by ardimasp** [comment]
Exactly. Intuitively there is an ANSI C char that allows you to clear screen and move your cursor position back to the top left of your screen.

**Comment by raizulfi** [comment]
ohhh I understand, I'll inform you again once I've implemented the code :)

**Comment by raizulfi** [comment]
hello sir I've added my implementation to clear the screen before each state transition. please let me know if that suffices.
